## Haftalık Ödev – Yaz Kampı: Veri Bilimi – Hafta 3 
Hedefler: 
- İleri seviye veri yapılarıyla (liste, sözlük, küme) rahatça çalışabilmesi, 
- Fonksiyonlar, lambda ve gömülü fonksiyonları etkin kullanabilmesi, 
- Modüller ve temel istatistiksel hesaplamaları uygulayabilmesi, 
- Kodlarını düzenli ve okunabilir şekilde yazabilmesi, 
- Basit bir veri analizi sürecini baştan sona gerçekleştirebilmesi beklenmektedir.

### Soru 1 – Liste Metotları 
Bir sınıfta öğrencilerin notları şu şekilde tutuluyor: 
notlar = [85, 92, 76, 92, 100, 76, 85, 92] 
- Listedeki tekrar eden notları silip benzersiz bir liste oluşturun. 
- En yüksek ve en düşük notu bulun. 
- Notları küçükten büyüğe sıralayın.

In [3]:
notes=[85,92,76,92,100,76,85,92]
newNotes=[]
for note in notes:
    if not note in newNotes:
        newNotes.append(note)
print(newNotes)
minNote=newNotes[0]
maxNote=newNotes[0]
for note in newNotes:
    if note<minNote:
        minNote=note
    if note>maxNote:
        maxNote=note
print(f"min : {minNote}, max : {maxNote}")
newNotes.sort()
print(newNotes)

[85, 92, 76, 100]
min : 76, max : 100
[76, 85, 92, 100]


### Soru 2 – Sayılar 
Bir sayının Armstrong sayısı olup olmadığını kontrol eden bir Python fonksiyonu yazın. 
Armstrong sayısı: Her basamağının küplerinin toplamı kendisine eşit olan sayılar. 
Örn: 153 → 1³+5³+3³ = 153

In [8]:
number=int(input("Bir Armstrong sayısı giriniz."))
stepValues=list(map(int,str(number)))

total=0
for i in stepValues:
    total+=pow(i,3)
if total==number:
    print("Bu bir Armstrong sayısıdır.")
else:
    print("Bu bir Armstrong sayısı değildir.")

Bu bir Armstrong sayısıdır.


### Soru 3 – Kümeler 
Aşağıdaki iki küme verilmiştir: 
A = {"Python", "R", "SQL", "Java"} 
B = {"C++", "Python", "JavaScript", "SQL"} 
- Ortak dilleri bulun. 
- Sadece A’da olan dilleri listeleyin. 
- İki kümenin birleşimini alfabetik olarak yazdırın.

In [9]:
A=["Python","R","SQL","Java"]
B=["C++","Python","Javascript","SQL"]
sameLanguages=[]
for language in A:
    if language in B:
        sameLanguages.append(language)
justInA=list(set(A)-set(sameLanguages))
totalGroup=[]
for language in A:
    if not language in B:
        totalGroup.append(language)
totalGroup+=B
totalGroup.sort()
print(f"Aynı diller : {sameLanguages}")
print(f"Sadece A listesinde olanlar : {justInA}")
print(f"İki kümenin alfabetik toplamı : {totalGroup}")


Aynı diller : ['Python', 'SQL']
Sadece A listesinde olanlar : ['R', 'Java']
İki kümenin alfabetik toplamı : ['C++', 'Java', 'Javascript', 'Python', 'R', 'SQL']


### Soru 4 – Modüller 
- random modülünü kullanarak 1–100 arasında 10 rastgele sayı üretin. 
- Bu sayıların ortalamasını ve standart sapmasını statistics modülü ile hesaplayın.

In [10]:
import random,statistics
numberList=[]
for i in range(1,11):
    numberList.append(random.randint(1,100))
mean=statistics.mean(numberList)
standartDeviation=statistics.stdev(numberList)
print(f"Ortalama : {mean}")
print(f"Standart Sapma : {standartDeviation}")

Ortalama : 43.8
Standart Sapma : 33.963378970754825


### Soru 5 – Fonksiyonlar 
kelime_sayacı(metin) adında bir fonksiyon yazın. 
Fonksiyon verilen metindeki: 
- toplam kelime sayısını 
- en uzun kelimeyi 
- en sık geçen kelimeyi döndürsün.

In [14]:
from collections import Counter
def kelime_sayaci(metin:str):
    kelimeler=metin.split()
    kelimelerinSayisi=Counter(kelimeler)
    enUzunKelime=kelimeler[0]
    toplamKelimeSayisi=0
    for i in kelimeler:
        toplamKelimeSayisi+=1
        if len(i)>len(enUzunKelime):
            enUzunKelime=i
    enCokGecenKelime,adet=kelimelerinSayisi.most_common(1)[0]
    return toplamKelimeSayisi,enUzunKelime,enCokGecenKelime
metin="Python veri bilimi derslerine hoşgeldiniz"
print(f"En çok geçen kelime : {kelime_sayaci(metin)[2]}\nEn uzun kelime : {kelime_sayaci(metin)[1]}\nToplam kelime sayısı : {kelime_sayaci(metin)[0]}")


En çok geçen kelime : Python
En uzun kelime : hoşgeldiniz
Toplam kelime sayısı : 5


### Soru 6 – Gömülü Fonksiyonlar 
Aşağıdaki liste için map, filter, sorted gibi gömülü fonksiyonları kullanarak: 
sayilar = [5, 12, 7, 18, 24, 3, 16] 
- Sadece çift sayıları filtreleyin. 
- Bu sayıların karelerini bulun. 
- Karelerini azalan sırada sıralayın.

In [16]:
sayilar=[5,12,7,18,24,3,16]
kareler=list(map(lambda x:x**2,sayilar)) 
ciftSayilar=list(filter(lambda x:x%2==0,sayilar)) 
karelerAzalanSira=sorted(sayilar,reverse=True)
print(f"Kareler : {kareler}\nÇift sayılar : {ciftSayilar}\nKareleri azalan sırada sıralanmış : {karelerAzalanSira}")

Kareler : [25, 144, 49, 324, 576, 9, 256]
Çift sayılar : [12, 18, 24, 16]
Kareleri azalan sırada sıralanmış : [24, 18, 16, 12, 7, 5, 3]


### Soru 7 – Lambda İfadeleri 
Aşağıdaki listeyi, her kelimenin uzunluğuna göre küçükten büyüğe sıralayın. 
kelimeler = ["veri", "bilim", "analiz", "yapayzeka", "python"] 
Bunu sorted + lambda ile yapın.

In [2]:
kelimeler=["veri","bilim","analiz","yapayzeka","python"]
kelimeler=sorted(kelimeler,key=lambda x:len(x))
print(kelimeler)

['veri', 'bilim', 'analiz', 'python', 'yapayzeka']


### Soru 8 – Metodlar 
Bir string içinde geçen tüm rakamları bulun ve bunların toplamını döndüren bir fonksiyon 
yazın. 
Örn: "abc12def3" → 12 + 3 = 15

In [4]:
def returnNumber(x:str):
    total=0
    for letter in x:
        if letter.isdigit():
            total+=int(letter)
    return total
print(returnNumber("ndfsvofd3234lkdsf546"))

27


### Soru 9 – (Ekstra) Numpy 1  
10 elemanlı bir numpy dizisi oluşturun. 
- Elemanlar 0–50 arasında rastgele sayılar olsun. 
- Dizinin ortalamasını, standart sapmasını ve en büyük değerini bulun.

In [8]:
import numpy as np
myNumpy=np.random.randint(0,51,size=10)
print(f"Sayılar : {myNumpy}")
print(f"Ortalaması : {np.mean(myNumpy)}")
print(f"Standart Sapma : {np.std(myNumpy)}")
print(f"Maksimum değer : {np.max(myNumpy)}")

Sayılar : [37 17 17 36 29  9 15  9 45 44]
Ortalaması : 25.8
Standart Sapma : 13.325164164091937
Maksimum değer : 45


### Soru 10 – (Ekstra) Numpy 2 
5x5 boyutunda rastgele 0–1 arasında değerlerden oluşan bir numpy matrisi üretin. 
- Her sütunun ortalamasını bulun. 
- 0.5’ten büyük olan değerleri 1, küçük eşit olanları 0 yaparak binary matris oluşturun.

In [10]:
import numpy as np 
matris=np.random.rand(5,5)
print(f"Matris : {matris}")
print(f"Ortalamalar : {np.mean(matris,axis=0)}")
binaryMatris=(matris>0.5).astype(int)
print(f"Binary matris : {binaryMatris}")

Matris : [[0.45222949 0.93522016 0.0688424  0.61090953 0.66969525]
 [0.82079812 0.01946198 0.6811112  0.15802971 0.05596445]
 [0.07047426 0.68201934 0.83299857 0.0145021  0.79895327]
 [0.51765324 0.2694863  0.13985865 0.9245502  0.17714043]
 [0.39014054 0.76859954 0.7798912  0.29861587 0.57130352]]
Ortalamalar : [0.45025913 0.53495746 0.5005404  0.40132148 0.45461138]
Binary matris : [[0 1 0 1 1]
 [1 0 1 0 0]
 [0 1 1 0 1]
 [1 0 0 1 0]
 [0 1 1 0 1]]
